version: '3.8'

services:
  # A2A Registry Service (runs with main app)
  registry:
    build: .
    container_name: a2a-registry
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - HANA_HOST=${HANA_HOST}
      - HANA_PORT=${HANA_PORT}
      - HANA_USER=${HANA_USER}
      - HANA_PASSWORD=${HANA_PASSWORD}
      - SQLITE_DB_PATH=/app/data/a2a_fallback.db
      - SQLITE_JOURNAL_MODE=WAL
    volumes:
      - ./data:/app/data
    networks:
      - a2a-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Agent 0 - Data Product Registration Agent
  agent0:
    build: .
    container_name: agent0-data-product
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
      - AGENT0_PORT=8002
      - AGENT0_HOST=0.0.0.0
      - A2A_REGISTRY_URL=http://registry:8000/api/v1/a2a
      - ORD_REGISTRY_URL=http://registry:8000/api/v1/ord
      - LOG_LEVEL=INFO
    command: python launch_agent0.py
    depends_on:
      - registry
    networks:
      - a2a-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Agent 1 - Financial Data Standardization Agent  
  agent1:
    build: .
    container_name: agent1-standardization
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - AGENT1_PORT=8001
      - AGENT1_HOST=0.0.0.0
      - A2A_REGISTRY_URL=http://registry:8000/api/v1/a2a
      - LOG_LEVEL=INFO
    command: python launch_agent1.py
    depends_on:
      - registry
    networks:
      - a2a-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Data Manager Agent (BDC Core) with Redis Cache
  data-manager:
    build: .
    container_name: data-manager-bdc-core
    ports:
      - "8003:8003"
    environment:
      - PYTHONPATH=/app
      - DATA_MANAGER_PORT=8003
      - DATA_MANAGER_HOST=0.0.0.0
      - A2A_REGISTRY_URL=http://registry:8000/api/v1/a2a
      - REDIS_URL=redis://data-manager-redis:6379
      - LOG_LEVEL=INFO
    command: python launch_data_manager.py
    depends_on:
      - registry
      - data-manager-redis
    networks:
      - a2a-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache for Data Manager Agent only
  data-manager-redis:
    image: redis:7-alpine
    container_name: data-manager-redis
    volumes:
      - data_manager_redis:/data
    networks:
      - a2a-network
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  data_manager_redis:

networks:
  a2a-network:
    driver: bridge