apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent2-ai-preparation
  namespace: a2a-network
  labels:
    app: agent2-ai-preparation
    agent-id: ai_preparation_agent_2
    a2a-role: enrichment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent2-ai-preparation
  template:
    metadata:
      labels:
        app: agent2-ai-preparation
        agent-id: ai_preparation_agent_2
        a2a-protocol: "0.2.9"
    spec:
      containers:
      - name: agent2
        image: a2a-network/agent2-ai-preparation:latest
        ports:
        - containerPort: 8003
          name: a2a
          protocol: TCP
        env:
        - name: AGENT_PORT
          value: "8003"
        - name: AGENT_BASE_URL
          value: "http://agent2-ai-preparation:8003"
        - name: DOWNSTREAM_AGENT_URL
          value: "http://agent3-vector-processing:8004"
        - name: AGENT_MANAGER_URL
          value: "http://agent-manager:8007"
        - name: AI_PREP_OUTPUT_DIR
          value: "/data/ai_prepared"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: agent2-ai-preparation
  namespace: a2a-network
  labels:
    app: agent2-ai-preparation
spec:
  selector:
    app: agent2-ai-preparation
  ports:
  - name: a2a
    port: 8003
    targetPort: 8003
    protocol: TCP
  type: ClusterIP