# A2A Platform Fly.io Configuration - Complete Platform
app = "a2a-platform"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "300s"

[build]
  image = "ghcr.io/plturrell/a2a-sap-network:main"

[env]
  A2A_ENVIRONMENT = "production"
  ENABLE_ALL_AGENTS = "true"
  A2A_NETWORK_ENABLED = "true"
  FRONTEND_ENABLED = "true"
  A2A_SERVICE_URL = "http://localhost:4004"
  A2A_SERVICE_HOST = "localhost"
  A2A_BASE_URL = "http://localhost:8000"
  A2A_AGENT_BASE_URL = "http://localhost:8000"
  A2A_IN_CONTAINER = "true"
  SKIP_VENV_CREATION = "true"
  STARTUP_MODE = "complete"

# Maximum resources for complete platform
[[vm]]
  cpu_kind = "performance"
  cpus = 16
  memory_mb = 65536
  size = "performance-16x"

[processes]
  app = "/app/start.sh complete"

[deploy]
  strategy = "immediate"
  max_unavailable = 1.0

# Single service with nginx proxy routing to all internal services
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[http_service.checks]]
    grace_period = "1800s"
    interval = "60s"
    timeout = "30s"
    path = "/health"

[metrics]
  port = 9091
  path = "/metrics"