# A2A Platform Fly.io Configuration - Complete Platform
app = "a2a-platform"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "300s"

[build]
  image = "ghcr.io/plturrell/a2a-sap-network:main"

[env]
  A2A_ENVIRONMENT = "production"
  ENABLE_ALL_AGENTS = "true"
  A2A_NETWORK_ENABLED = "true"
  FRONTEND_ENABLED = "true"
  A2A_SERVICE_URL = "http://localhost:4004"
  A2A_SERVICE_HOST = "localhost"
  A2A_BASE_URL = "http://localhost:8000"
  A2A_AGENT_BASE_URL = "http://localhost:8000"
  A2A_IN_CONTAINER = "true"
  SKIP_VENV_CREATION = "true"
  STARTUP_MODE = "complete"

# Start with reasonable resources
[[vm]]
  cpu_kind = "performance"
  cpus = 8
  memory_mb = 16384

[processes]
  app = "backend"

[deploy]
  strategy = "immediate"
  max_unavailable = 1.0

# Main Agent Service on port 8000
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "600s"
    interval = "60s"
    timeout = "30s"
    path = "/health"
    method = "GET"
    type = "http"

[metrics]
  port = 9091
  path = "/metrics"