export enum ErrorCode {
  INVALID_ADDRESS = 'INVALID_ADDRESS',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  NETWORK_ERROR = 'NETWORK_ERROR',
  CONTRACT_ERROR = 'CONTRACT_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  INVALID_CONFIG = 'INVALID_CONFIG',
  UNSUPPORTED_NETWORK = 'UNSUPPORTED_NETWORK',
  NO_PROVIDER = 'NO_PROVIDER',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  WRONG_NETWORK = 'WRONG_NETWORK',
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  DISCONNECTION_FAILED = 'DISCONNECTION_FAILED',
  NO_CONTRACTS = 'NO_CONTRACTS',
  WEBSOCKET_ERROR = 'WEBSOCKET_ERROR',
  INVALID_MESSAGE = 'INVALID_MESSAGE',
  CONNECTION_TIMEOUT = 'CONNECTION_TIMEOUT',
  RECONNECTION_FAILED = 'RECONNECTION_FAILED',
  CONTRACT_NOT_FOUND = 'CONTRACT_NOT_FOUND',
  WEBSOCKET_NOT_CONNECTED = 'WEBSOCKET_NOT_CONNECTED',
  NO_SIGNER = 'NO_SIGNER',
  SEND_FAILED = 'SEND_FAILED',
  FETCH_FAILED = 'FETCH_FAILED',
  UPDATE_FAILED = 'UPDATE_FAILED',
  DELETE_FAILED = 'DELETE_FAILED',
  CALCULATION_FAILED = 'CALCULATION_FAILED',
  INVALID_PARAMS = 'INVALID_PARAMS',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',
  STATUS_UPDATE_FAILED = 'STATUS_UPDATE_FAILED',
  DEREGISTRATION_FAILED = 'DEREGISTRATION_FAILED',
  ESTIMATION_FAILED = 'ESTIMATION_FAILED',
  INVALID_CONTRACT_ADDRESS = 'INVALID_CONTRACT_ADDRESS',
  SEARCH_FAILED = 'SEARCH_FAILED'
}

export class A2AError extends Error {
  public code: ErrorCode;
  public details?: unknown;

  constructor(code: ErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = 'A2AError';
    this.code = code;
    this.details = details;
  }
}

export function createError(code: ErrorCode, message: string, details?: unknown): A2AError {
  return new A2AError(code, message, details);
}