apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-manager
  namespace: a2a-network
  labels:
    app: catalog-manager
    component: catalog
    a2a-agent: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-manager
  template:
    metadata:
      labels:
        app: catalog-manager
        component: catalog
        a2a-agent: "true"
    spec:
      containers:
      - name: catalog-manager
        image: a2a/catalog-manager:latest
        ports:
        - containerPort: 8009
        env:
        - name: AGENT_PORT
          value: "8009"
        - name: AGENT_BASE_URL
          value: "http://catalog-manager:8009"
        - name: AGENT_MANAGER_URL
          value: "http://agent-manager:8007"
        - name: DATA_MANAGER_URL
          value: "http://data-manager:8008"
        - name: CATALOG_DB_PATH
          value: "/data/a2a_catalog.db"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: CACHE_TTL
          value: "3600"
        volumeMounts:
        - name: catalog-storage
          mountPath: /data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8009
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8009
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: catalog-storage
        persistentVolumeClaim:
          claimName: catalog-manager-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-manager
  namespace: a2a-network
  labels:
    app: catalog-manager
    component: catalog
spec:
  selector:
    app: catalog-manager
  ports:
  - port: 8009
    targetPort: 8009
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-manager-pvc
  namespace: a2a-network
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard