apiVersion: v1
kind: ConfigMap
metadata:
  name: a2a-config
  namespace: a2a-network
data:
  # A2A Network Configuration
  A2A_PROTOCOL_VERSION: "0.2.9"
  AGENT_MANAGER_URL: "http://agent-manager:8007"
  
  # ORD Registry
  ORD_REGISTRY_URL: "http://ord-registry:8000/api/v1/ord"
  
  # Service URLs (for agent discovery)
  AGENT0_URL: "http://agent0-data-product:8001"
  AGENT1_URL: "http://agent1-standardization:8002"
  AGENT2_URL: "http://agent2-ai-preparation:8003"
  AGENT3_URL: "http://agent3-vector-processing:8004"
  DATA_MANAGER_URL: "http://data-manager:8005"
  CATALOG_MANAGER_URL: "http://catalog-manager:8006"
  
  # Monitoring
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  PROMETHEUS_PUSHGATEWAY: "http://prometheus-pushgateway:9091"
  
  # Logging
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"