apiVersion: v1
kind: Secret
metadata:
  name: a2a-secrets
  namespace: a2a-network
type: Opaque
stringData:
  # Trust Contract (example - replace with actual)
  trust-contract-address: "0x1234567890abcdef1234567890abcdef12345678"
  
  # Database Credentials (example - replace with actual)
  supabase-url: "https://your-project.supabase.co"
  supabase-key: "your-supabase-anon-key"
  hana-host: "your-hana-host.hanacloud.ondemand.com"
  hana-port: "30015"
  hana-user: "system"
  hana-password: "your-hana-password"
  
  # Redis
  redis-password: "your-redis-password"
  
  # API Keys (if needed)
  grok-api-key: "your-grok-api-key"
  perplexity-api-key: "your-perplexity-api-key"