# A2A Business Data Cloud Production Configuration

deployment:
  environment: production
  region: us-east-1
  availability_zones:
    - us-east-1a
    - us-east-1b
  
blockchain:
  network: ethereum-mainnet
  rpc_url: ${ETHEREUM_RPC_URL}
  contracts:
    BusinessDataCloudA2A: ${BDC_CONTRACT_ADDRESS}
    AgentRegistry: ${REGISTRY_CONTRACT_ADDRESS}
    MessageRouter: ${ROUTER_CONTRACT_ADDRESS}
  gas_settings:
    max_gas_price: 100
    gas_multiplier: 1.2
    
services:
  data_manager:
    replicas: 3
    port: 8001
    resources:
      cpu: 2
      memory: 4Gi
    database:
      primary:
        type: hana
        connection_string: ${HANA_CONNECTION_STRING}
        pool_size: 20
      fallback:
        type: supabase
        url: ${SUPABASE_URL}
        key: ${SUPABASE_KEY}
    health_check:
      path: /health
      interval: 30s
      timeout: 5s
      
  catalog_manager:
    replicas: 2
    port: 8002
    resources:
      cpu: 1
      memory: 2Gi
    ord_registry:
      url: ${ORD_REGISTRY_URL}
      cache_ttl: 300
    elasticsearch:
      url: ${ELASTICSEARCH_URL}
      index: catalog_production
      
  agent0_data_product:
    replicas: 2
    port: 8003
    resources:
      cpu: 1
      memory: 2Gi
    features:
      dublin_core: true
      blockchain_registration: true
      
  agent1_standardization:
    replicas: 2
    port: 8004
    resources:
      cpu: 1.5
      memory: 3Gi
    standardizers:
      - account_standardizer
      - product_standardizer
      - location_standardizer
      - measure_standardizer
      
  agent2_ai_preparation:
    replicas: 3
    port: 8005
    resources:
      cpu: 2
      memory: 4Gi
    grok_api:
      url: ${GROK_API_URL}
      key: ${GROK_API_KEY}
      model: grok-1
      rate_limit: 100
      
  agent3_vector_processing:
    replicas: 2
    port: 8008
    resources:
      cpu: 3
      memory: 8Gi
      gpu: 1
    vector_store:
      type: pinecone
      api_key: ${PINECONE_API_KEY}
      environment: ${PINECONE_ENV}
      
  agent4_calc_validation:
    replicas: 2
    port: 8006
    resources:
      cpu: 2
      memory: 4Gi
    validation:
      timeout: 60s
      max_retries: 3
      
  agent5_qa_validation:
    replicas: 2
    port: 8007
    resources:
      cpu: 2
      memory: 4Gi
    simpleqa:
      enabled: true
      confidence_threshold: 0.8

monitoring:
  prometheus:
    enabled: true
    port: 9090
    retention: 30d
  grafana:
    enabled: true
    port: 3000
    dashboards:
      - a2a_overview
      - agent_metrics
      - blockchain_transactions
  alerts:
    slack_webhook: ${SLACK_WEBHOOK_URL}
    pagerduty_key: ${PAGERDUTY_KEY}
    
security:
  tls:
    enabled: true
    cert_path: /etc/ssl/certs/a2a.crt
    key_path: /etc/ssl/private/a2a.key
  authentication:
    type: oauth2
    provider: auth0
    client_id: ${AUTH0_CLIENT_ID}
    client_secret: ${AUTH0_CLIENT_SECRET}
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst: 150
    
networking:
  load_balancer:
    type: application
    health_check_path: /health
    ssl_policy: ELBSecurityPolicy-TLS-1-2-2017-01
  service_mesh:
    enabled: true
    type: istio
    mtls: true
    
backup:
  enabled: true
  schedule: "0 2 * * *"  # 2 AM daily
  retention_days: 30
  destinations:
    - s3://a2a-backups-prod
    
logging:
  level: INFO
  format: json
  destinations:
    - cloudwatch
    - elasticsearch
  retention_days: 90
  
scaling:
  enabled: true
  metrics:
    - cpu_utilization
    - memory_utilization
    - request_count
  cpu_threshold: 70
  memory_threshold: 80
  min_replicas: 2
  max_replicas: 10
  
disaster_recovery:
  multi_region: true
  backup_region: us-west-2
  rpo_minutes: 15  # Recovery Point Objective
  rto_minutes: 30  # Recovery Time Objective