# Prometheus Configuration for A2A Platform Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'a2a-platform'
    environment: '${ENVIRONMENT:-development}'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # A2A Platform services
  - job_name: 'a2a-network'
    static_configs:
      - targets: ['a2a-network:4004']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  - job_name: 'a2a-agents'
    static_configs:
      - targets: ['a2a-agents:8000']
    metrics_path: '/health/performance'
    scrape_interval: 15s
    metric_relabeling_configs:
      - source_labels: [__name__]
        regex: 'a2a_(.*)'
        target_label: __name__
        replacement: 'a2a_agent_${1}'

  # Enhanced Glean Agent metrics
  - job_name: 'glean-agent'
    static_configs:
      - targets: ['localhost:8001'] # Assuming Glean agent runs on 8001
    metrics_path: '/metrics'
    scrape_interval: 5s
    honor_timestamps: true
    params:
      format: ['prometheus']

  # System metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Container metrics (cAdvisor)  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Database metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Application Performance Monitoring
  - job_name: 'a2a-performance'
    static_configs:
      - targets: ['a2a-network:4004', 'a2a-agents:8000']
    metrics_path: '/health/performance'
    scrape_interval: 10s
    honor_labels: true

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

# Remote write configuration for long-term storage
remote_write:
  - url: "${REMOTE_WRITE_URL:-http://localhost:8086/api/v1/prom/write}"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 500