jQuery.sap.registerPreloadedModules({
    "version": "2.0",
    "modules": {
        "a2a/network/fiori/Component.js"() {
            // This is a placeholder Component-preload.js file
            // In a real application, this would be generated by the UI5 build process
            // and contain minified versions of all component modules
            sap.ui.define([
                "sap/ui/core/UIComponent"
            ], function(UIComponent) {
                "use strict";
                return UIComponent.extend("a2a.network.fiori.Component", {
                    metadata: {
                        manifest: "json"
                    }
                });
            });
        },
        "a2a/network/fiori/manifest.json": JSON.stringify({
            "_version": "1.60.0",
            "sap.app": {
                "id": "a2a.network.fiori",
                "type": "application"
            }
        })
    }
});