# A2A Platform Fly.io Configuration
app = "a2a-platform"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "ghcr.io/plturrell/a2a-sap-network:main"

[env]
  PORT = "8080"
  A2A_ENVIRONMENT = "production"
  ENABLE_ALL_AGENTS = "true"
  A2A_NETWORK_ENABLED = "true"
  FRONTEND_ENABLED = "true"
  A2A_SERVICE_URL = "http://localhost:4004"
  A2A_SERVICE_HOST = "localhost"
  A2A_BASE_URL = "http://localhost:8000"
  A2A_AGENT_BASE_URL = "http://localhost:8000"
  A2A_IN_CONTAINER = "true"
  SKIP_VENV_CREATION = "true"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
    
  [[services.tcp_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "120s"
    restart_limit = 3

# Launch Pad / Frontend
[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]
  
  [[services.ports]]
    port = 3000
    handlers = ["http"]

# A2A Network API
[[services]]
  protocol = "tcp"
  internal_port = 4004
  processes = ["app"]
  
  [[services.ports]]
    port = 4004
    handlers = ["http"]

# Agent Services (8000-8017)
[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]
  
  [[services.ports]]
    port = 8000
    handlers = ["http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory_mb = 4096

[processes]
  app = "/app/start.sh complete"

[deploy]
  strategy = "rolling"
  max_unavailable = 0.2

[metrics]
  port = 9091
  path = "/metrics"