version: '3.8'

services:
  # Agent 0 - Data Product Registration
  agent0-data-product:
    build:
      context: ..
      dockerfile: services/agent0_data_product/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - AGENT_PORT=8001
      - AGENT_BASE_URL=http://agent0-data-product:8001
      - ORD_REGISTRY_URL=http://ord-registry:8000/api/v1/ord
      - DOWNSTREAM_AGENT_URL=http://agent1-standardization:8002
    networks:
      - a2a-network
    depends_on:
      - ord-registry

  # Agent 1 - Data Standardization
  agent1-standardization:
    build:
      context: ..
      dockerfile: services/agent1_standardization/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - AGENT_PORT=8002
      - AGENT_BASE_URL=http://agent1-standardization:8002
      - DOWNSTREAM_AGENT_URL=http://agent2-ai-preparation:8003
    networks:
      - a2a-network

  # Agent 2 - AI Preparation
  agent2-ai-preparation:
    build:
      context: ..
      dockerfile: services/agent2_ai_preparation/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - AGENT_PORT=8003
      - AGENT_BASE_URL=http://agent2-ai-preparation:8003
      - DOWNSTREAM_AGENT_URL=http://agent3-vector-processing:8004
    networks:
      - a2a-network

  # Agent 3 - Vector Processing
  agent3-vector-processing:
    build:
      context: ..
      dockerfile: services/agent3_vector_processing/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - AGENT_PORT=8004
      - AGENT_BASE_URL=http://agent3-vector-processing:8004
      - HANA_HOST=${HANA_HOST}
      - HANA_PORT=${HANA_PORT}
      - HANA_USER=${HANA_USER}
      - HANA_PASSWORD=${HANA_PASSWORD}
    networks:
      - a2a-network

  # Agent Manager - Orchestration
  agent-manager:
    build:
      context: ..
      dockerfile: services/agent_manager/Dockerfile
    ports:
      - "8007:8007"
    environment:
      - AGENT_PORT=8007
      - AGENT_BASE_URL=http://agent-manager:8007
    networks:
      - a2a-network

  # Data Manager - Storage & CRUD
  data-manager:
    build:
      context: ..
      dockerfile: services/data_manager/Dockerfile
    ports:
      - "8005:8005"
    environment:
      - AGENT_PORT=8005
      - AGENT_BASE_URL=http://data-manager:8005
      - SQLITE_DATABASE_PATH=/app/data/a2a.db
      - SQLITE_BACKUP_PATH=/app/backups/
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    networks:
      - a2a-network

  # Catalog Manager - ORD Registry Interface
  catalog-manager:
    build:
      context: ..
      dockerfile: services/catalog_manager/Dockerfile
    ports:
      - "8006:8006"
    environment:
      - AGENT_PORT=8006
      - AGENT_BASE_URL=http://catalog-manager:8006
      - ORD_REGISTRY_URL=http://ord-registry:8000/api/v1/ord
    networks:
      - a2a-network

  # ORD Registry (external service)
  ord-registry:
    image: ord-registry:latest
    ports:
      - "8000:8000"
    networks:
      - a2a-network

networks:
  a2a-network:
    driver: bridge