version: '3.8'

services:
  # Infrastructure Services
  redis:
    image: redis:7-alpine
    restart: always
    mem_limit: 512m
    mem_reservation: 256m
    networks:
      - a2a-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    restart: always
    mem_limit: 1g
    mem_reservation: 512m
    environment:
      POSTGRES_USER: a2a
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-a2apass}
      POSTGRES_DB: a2a_platform
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - a2a-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U a2a"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Agent 0 - Registry Server
  agent-0-registry:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      AGENT_ID: "0"
      AGENT_TYPE: "registry"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "0"]

  # Agent 1 - Manager
  agent-1-manager:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      AGENT_ID: "1"
      AGENT_TYPE: "manager"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8001:8001"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "1"]

  # Agent 2 - Calculator
  agent-2-calculator:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "2"
      AGENT_TYPE: "calculator"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8002:8002"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "2"]

  # Agent 3 - Trust Manager
  agent-3-trust:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "3"
      AGENT_TYPE: "trust"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8003:8003"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "3"]

  # Agent 4 - Security Monitor
  agent-4-security:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "4"
      AGENT_TYPE: "security"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8004:8004"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "4"]

  # Agent 5 - Persistence Manager
  agent-5-persistence:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "5"
      AGENT_TYPE: "persistence"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8005:8005"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "5"]

  # Agent 6 - Data Processor
  agent-6-data:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "6"
      AGENT_TYPE: "data_processor"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8006:8006"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "6"]

  # Agent 7 - Analytics
  agent-7-analytics:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "7"
      AGENT_TYPE: "analytics"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8007:8007"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "7"]

  # Agent 8 - Communication Hub
  agent-8-comm:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "8"
      AGENT_TYPE: "communication"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8008:8008"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "8"]

  # Agent 9 - Task Scheduler
  agent-9-scheduler:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "9"
      AGENT_TYPE: "scheduler"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8009:8009"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "9"]

  # Agent 10 - Resource Monitor
  agent-10-resource:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "10"
      AGENT_TYPE: "resource_monitor"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8010:8010"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "10"]

  # Agent 11 - Compliance Checker
  agent-11-compliance:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "11"
      AGENT_TYPE: "compliance"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8011:8011"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "11"]

  # Agent 12 - Integration Bridge
  agent-12-integration:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "12"
      AGENT_TYPE: "integration"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8012:8012"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "12"]

  # Agent 13 - Backup Manager
  agent-13-backup:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "13"
      AGENT_TYPE: "backup"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8013:8013"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "13"]

  # Agent 14 - Notification Service
  agent-14-notification:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "14"
      AGENT_TYPE: "notification"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8014:8014"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "14"]

  # Agent 15 - Audit Logger
  agent-15-audit:
    image: ghcr.io/plturrell/a2a-sap-network:latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      AGENT_ID: "15"
      AGENT_TYPE: "audit"
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - "8015:8015"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network
    command: ["python", "-m", "a2aAgents.backend.main", "--agent-id", "15"]

  # CDS/CAP Network Service
  cds-service:
    image: finsightintelligence/a2a:network-latest
    restart: always
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://a2a:${POSTGRES_PASSWORD:-a2apass}@postgres:5432/a2a_platform
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    networks:
      - a2a-network

  # Frontend UI (Optional - can be served statically)
  frontend:
    image: finsightintelligence/a2a:frontend-latest
    restart: always
    mem_limit: 256m
    mem_reservation: 128m
    environment:
      REACT_APP_API_URL: http://agent-0-registry:8000
    ports:
      - "3001:80"
    depends_on:
      - agent-0-registry
    networks:
      - a2a-network

networks:
  a2a-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local