# Base Configuration - Common settings across all environments
# This file contains default values that can be overridden by environment-specific configs

database:
  pool_min_size: 5
  pool_max_size: 20
  pool_timeout: 30
  ssl_mode: "prefer"
  connect_timeout: 10
  command_timeout: 30

redis:
  max_connections: 100
  timeout: 5
  retry_on_timeout: true
  health_check_interval: 30

security:
  jwt_algorithm: "HS256"
  jwt_expiry_hours: 24
  jwt_refresh_expiry_days: 7
  password_min_length: 12
  session_timeout_minutes: 30
  max_login_attempts: 5
  lockout_duration_minutes: 15

cors:
  methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  credentials: true
  max_age: 3600

agents:
  timeout_seconds: 30
  max_retries: 3
  retry_delay_seconds: 2
  max_concurrent_requests: 100
  health_check_interval: 30
  processing_batch_size: 10
  # Agent-specific timeouts
  agent0_timeout: 15
  agent1_timeout: 45
  agent2_timeout: 120
  agent3_timeout: 60
  agent4_timeout: 90
  agent5_timeout: 30

external_services:
  grok_api_url: "https://api.x.ai/v1/chat/completions"
  perplexity_api_url: "https://api.perplexity.ai"
  api_timeout_seconds: 30
  max_requests_per_minute: 60
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60

monitoring:
  enable_metrics: true
  enable_tracing: true
  enable_logging: true
  otel_service_name: "a2a-agents"
  otel_service_version: "1.0.0"
  log_level: "INFO"
  log_format: "json"
  log_file_max_size: 100
  log_file_backup_count: 5
  metrics_port: 9090
  metrics_path: "/metrics"
  health_check_timeout: 5
  health_check_interval: 30

notifications:
  page_size: 20
  max_notifications: 1000
  retention_days: 30
  batch_size: 100
  error_threshold: 10
  warning_threshold: 25
  performance_threshold_ms: 1000

ui:
  default_page_size: 20
  max_page_size: 100
  api_timeout_ms: 30000
  chart_load_timeout_ms: 10000
  file_upload_timeout_ms: 300000
  max_file_size_mb: 50
  max_concurrent_uploads: 3
  enable_dark_mode: true
  enable_analytics: false
  enable_debug_mode: false