"""
A2A Network Error Handling

Error classes and error code definitions for A2A Network SDK.
"""

class ErrorCode:
    """Error code constants"""
    INVALID_CONFIG = "INVALID_CONFIG"
    UNSUPPORTED_NETWORK = "UNSUPPORTED_NETWORK"
    NO_PROVIDER = "NO_PROVIDER"
    INVALID_PRIVATE_KEY = "INVALID_PRIVATE_KEY"
    CONNECTION_FAILED = "CONNECTION_FAILED"
    WRONG_NETWORK = "WRONG_NETWORK"
    DISCONNECTION_FAILED = "DISCONNECTION_FAILED"
    NO_CONTRACTS = "NO_CONTRACTS"
    INVALID_CONTRACT_ADDRESS = "INVALID_CONTRACT_ADDRESS"
    CONTRACT_INITIALIZATION_FAILED = "CONTRACT_INITIALIZATION_FAILED"
    CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND"
    WEBSOCKET_ERROR = "WEBSOCKET_ERROR"
    WEBSOCKET_NOT_CONNECTED = "WEBSOCKET_NOT_CONNECTED"
    NETWORK_INFO_FAILED = "NETWORK_INFO_FAILED"
    INVALID_PARAMS = "INVALID_PARAMS"
    NO_SIGNER = "NO_SIGNER"
    REGISTRATION_FAILED = "REGISTRATION_FAILED"
    UPDATE_FAILED = "UPDATE_FAILED"
    FETCH_FAILED = "FETCH_FAILED"
    SEARCH_FAILED = "SEARCH_FAILED"
    STATUS_UPDATE_FAILED = "STATUS_UPDATE_FAILED"
    UNAUTHORIZED = "UNAUTHORIZED"
    DEREGISTRATION_FAILED = "DEREGISTRATION_FAILED"
    ESTIMATION_FAILED = "ESTIMATION_FAILED"
    INVALID_ADDRESS = "INVALID_ADDRESS"

class A2AError(Exception):
    """Base A2A Network error"""
    def __init__(self, code, message):
        self.code = code
        self.message = message
        super().__init__(message)

__all__ = ['A2AError', 'ErrorCode']